export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const LOAD_PLANTS = 'LOAD_PLANTS'
export const LOAD_FAVORITES = 'LOAD_FAVORITES'
export const TOGGLE_OPEN = 'TOGGLE_OPEN'
export const TOGGLE_CLOSE = 'TOGGLE_CLOSE'
